tap "homebrew/cask-versions"

brew "node"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "watch"

cask "android-studio"
cask "flux"
cask "google-chrome"
cask "google-chrome-beta"
cask "iterm2"
cask "messenger"
cask "ngrok"
cask "rode-connect"
cask "sequel-ace"
cask "slack"
cask "sonos"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
cask "xcodes"
cask "zoom"
