brew "tmux"
brew "tmuxinator"
brew "tree"
brew "watch"

tap "homebrew/cask-versions"

cask "android-studio"
cask "google-chrome"
cask "google-chrome-beta"
cask "iterm2"
cask "ngrok"
cask "sequel-ace"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
